sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: EmF+M9rbz3BBEy0OZ41dMtJ33UtKrm7TVeChX86yy633ZchqMwgdijFiW/DNVjYpnw6B1VDWTK1np23c6TCyucjp0rIEUrma2NUCnOhkeN5hdc8YpkOKyfWRQsL6HruA1kSHRMQaKgjWvVJ6qEKqPysryaKKy6Rpyaha3njAZvIGfp6149DeXvbLiLCQ1xY9rfpz1SQEge4rSnjrsxIMqeq9Vu7xS+WDv+ZgmJ9IQLkyQjuV0eJ01vhq3mnk/x/7MIm3PEnbBIEDrNOGuVW9Z0+MvOkracNgWT/n27Le7B04bbfqZeR3wKlj2ir95yJCxjVfRE3DJaMu+zkZOERAup9cjJQySVSY+CGbEYTqrVmGclEWkFdn/9YO2HBsKqcHoQf5fTD5gRLnWKTeW1sz0c9YHjqEWAKPr16s77KpvXXOjz7oE6L2lpD+HO+nZPW67PqbYMMTYk0pZhBe25O8QWMNeohPdtRYuh2M42nq3Eyk6Olx7UAANTlqTq0jGHppwikrd6yY2Eg9c3Dh8CvSIFqYkIkJ+47CeSliJZjThHAdRuQ4mlV0FFdCDw9IQmcn6zF+rwtK6IxEUtk5bIyGVWWBjkObyLhRC9Y4bOm91YLabXunSwJ/18+wP8DKOK5k4ANzccHoeQ+FTwoW8cqDtZKrkRavUMUeVjLXLEN8xcE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Tartarin-of-Tarascon_1862
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy